import type { NextConfig } from "next";

const securityHeaders = [
  { key: "X-Frame-Options", value: "DENY" },
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=()",
  },
];

// OLD WORDPRESS URL → NEW NEXT.JS URL
// All WP pages had trailing slashes, handled via permanent: true 301 redirects
const redirects = [

  // ── Old WP Pages — map to nearest equivalent ──────────────────────────────
  { source: "/cpg-marketing-agency",              destination: "/cpg",                           permanent: true },
  { source: "/cpg-marketing-agency/",             destination: "/cpg",                           permanent: true },
  { source: "/seo-agency-san-antonio",            destination: "/services/seo-san-antonio",      permanent: true },
  { source: "/seo-agency-san-antonio/",           destination: "/services/seo-san-antonio",      permanent: true },
  { source: "/why-choose-beast-creative-agency",  destination: "/about",                         permanent: true },
  { source: "/why-choose-beast-creative-agency/", destination: "/about",                         permanent: true },
  { source: "/dermatology-marketing-case-study",  destination: "/work",                          permanent: true },
  { source: "/dermatology-marketing-case-study/", destination: "/work",                          permanent: true },
  { source: "/graphic-design-san-antonio",        destination: "/services/branding",             permanent: true },
  { source: "/graphic-design-san-antonio/",       destination: "/services/branding",             permanent: true },
  { source: "/web-design-development-san-antonio",  destination: "/services/web-design-san-antonio", permanent: true },
  { source: "/web-design-development-san-antonio/", destination: "/services/web-design-san-antonio", permanent: true },
  { source: "/logo-design-san-antonio",           destination: "/services/logo-design-san-antonio", permanent: true },
  { source: "/logo-design-san-antonio/",          destination: "/services/logo-design-san-antonio", permanent: true },
  { source: "/branding-agency-san-antonio",       destination: "/services/branding",             permanent: true },
  { source: "/branding-agency-san-antonio/",      destination: "/services/branding",             permanent: true },
  { source: "/social-media-marketing-san-antonio",  destination: "/services/paid-media",         permanent: true },
  { source: "/social-media-marketing-san-antonio/", destination: "/services/paid-media",         permanent: true },
  { source: "/team",                              destination: "/about",                         permanent: true },
  { source: "/team/",                             destination: "/about",                         permanent: true },
  { source: "/privacy-policy",                   destination: "/privacy",                        permanent: true },
  { source: "/privacy-policy/",                  destination: "/privacy",                        permanent: true },
  { source: "/branding-case-study",              destination: "/work/coinline",                  permanent: true },
  { source: "/branding-case-study/",             destination: "/work/coinline",                  permanent: true },

  // ── Blog posts that exist on new site — root slug → /blog/slug ──────────
  { source: "/amazon-advertising-for-cpg-brands-ppc-strategies-to-win-the-buy-box",              destination: "/blog/amazon-advertising-for-cpg-brands-ppc-strategies-to-win-the-buy-box",              permanent: true },
  { source: "/amazon-advertising-for-cpg-brands-ppc-strategies-to-win-the-buy-box/",             destination: "/blog/amazon-advertising-for-cpg-brands-ppc-strategies-to-win-the-buy-box",              permanent: true },
  { source: "/amazon-vs-dtc-for-cpg-brands-which-channel-should-you-prioritize",                 destination: "/blog/amazon-vs-dtc-for-cpg-brands-which-channel-should-you-prioritize",                 permanent: true },
  { source: "/amazon-vs-dtc-for-cpg-brands-which-channel-should-you-prioritize/",                destination: "/blog/amazon-vs-dtc-for-cpg-brands-which-channel-should-you-prioritize",                 permanent: true },
  { source: "/building-a-cpg-brand-community-email-sms-and-loyalty-programs-for-packaged-goods",  destination: "/blog/building-a-cpg-brand-community-email-sms-and-loyalty-programs-for-packaged-goods",  permanent: true },
  { source: "/building-a-cpg-brand-community-email-sms-and-loyalty-programs-for-packaged-goods/", destination: "/blog/building-a-cpg-brand-community-email-sms-and-loyalty-programs-for-packaged-goods",  permanent: true },
  { source: "/cpg-ad-creative-that-converts-testing-iteration-and-best-practices",                destination: "/blog/cpg-ad-creative-that-converts-testing-iteration-and-best-practices",                permanent: true },
  { source: "/cpg-ad-creative-that-converts-testing-iteration-and-best-practices/",               destination: "/blog/cpg-ad-creative-that-converts-testing-iteration-and-best-practices",                permanent: true },
  { source: "/cpg-advertising-strategy-choosing-the-right-paid-channels-for-your-budget",         destination: "/blog/cpg-advertising-strategy-choosing-the-right-paid-channels-for-your-budget",         permanent: true },
  { source: "/cpg-advertising-strategy-choosing-the-right-paid-channels-for-your-budget/",        destination: "/blog/cpg-advertising-strategy-choosing-the-right-paid-channels-for-your-budget",         permanent: true },
  { source: "/cpg-brand-refresh-when-and-how-to-rebrand-your-consumer-packaged-goods",            destination: "/blog/cpg-brand-refresh-when-and-how-to-rebrand-your-consumer-packaged-goods",            permanent: true },
  { source: "/cpg-brand-refresh-when-and-how-to-rebrand-your-consumer-packaged-goods/",           destination: "/blog/cpg-brand-refresh-when-and-how-to-rebrand-your-consumer-packaged-goods",            permanent: true },
  { source: "/cpg-brand-storytelling-connecting-with-consumers-through-authentic-narratives",      destination: "/blog/cpg-brand-storytelling-connecting-with-consumers-through-authentic-narratives",      permanent: true },
  { source: "/cpg-brand-storytelling-connecting-with-consumers-through-authentic-narratives/",     destination: "/blog/cpg-brand-storytelling-connecting-with-consumers-through-authentic-narratives",      permanent: true },
  { source: "/cpg-brand-strategy-how-to-position-your-consumer-packaged-goods-in-a-crowded-market",  destination: "/blog/cpg-brand-strategy-how-to-position-your-consumer-packaged-goods-in-a-crowded-market",  permanent: true },
  { source: "/cpg-brand-strategy-how-to-position-your-consumer-packaged-goods-in-a-crowded-market/", destination: "/blog/cpg-brand-strategy-how-to-position-your-consumer-packaged-goods-in-a-crowded-market",  permanent: true },
  { source: "/cpg-commodity-price-volatility-managing-input-cost-fluctuations",                   destination: "/blog/cpg-commodity-price-volatility-managing-input-cost-fluctuations",                   permanent: true },
  { source: "/cpg-commodity-price-volatility-managing-input-cost-fluctuations/",                  destination: "/blog/cpg-commodity-price-volatility-managing-input-cost-fluctuations",                   permanent: true },
  { source: "/cpg-content-marketing-creating-content-that-educates-and-converts-consumers",        destination: "/blog/cpg-content-marketing-creating-content-that-educates-and-converts-consumers",        permanent: true },
  { source: "/cpg-content-marketing-creating-content-that-educates-and-converts-consumers/",       destination: "/blog/cpg-content-marketing-creating-content-that-educates-and-converts-consumers",        permanent: true },
  { source: "/cpg-counterfeit-products-protecting-your-brand-from-fraud",                         destination: "/blog/cpg-counterfeit-products-protecting-your-brand-from-fraud",                         permanent: true },
  { source: "/cpg-counterfeit-products-protecting-your-brand-from-fraud/",                        destination: "/blog/cpg-counterfeit-products-protecting-your-brand-from-fraud",                         permanent: true },
  { source: "/cpg-ecommerce-conversion-optimization-turning-browsers-into-buyers",                 destination: "/blog/cpg-ecommerce-conversion-optimization-turning-browsers-into-buyers",                 permanent: true },
  { source: "/cpg-ecommerce-conversion-optimization-turning-browsers-into-buyers/",                destination: "/blog/cpg-ecommerce-conversion-optimization-turning-browsers-into-buyers",                 permanent: true },
  { source: "/cpg-funding-options-from-bootstrapping-to-venture-capital",                          destination: "/blog/cpg-funding-options-from-bootstrapping-to-venture-capital",                          permanent: true },
  { source: "/cpg-funding-options-from-bootstrapping-to-venture-capital/",                         destination: "/blog/cpg-funding-options-from-bootstrapping-to-venture-capital",                          permanent: true },
  { source: "/cpg-packaging-design-and-marketing-how-your-package-sells-your-product",             destination: "/blog/cpg-packaging-design-and-marketing-how-your-package-sells-your-product",             permanent: true },
  { source: "/cpg-packaging-design-and-marketing-how-your-package-sells-your-product/",            destination: "/blog/cpg-packaging-design-and-marketing-how-your-package-sells-your-product",             permanent: true },
  { source: "/cpg-performance-marketing-attribution-cac-and-roas-optimization",                    destination: "/blog/cpg-performance-marketing-attribution-cac-and-roas-optimization",                    permanent: true },
  { source: "/cpg-performance-marketing-attribution-cac-and-roas-optimization/",                   destination: "/blog/cpg-performance-marketing-attribution-cac-and-roas-optimization",                    permanent: true },
  { source: "/cpg-profitability-analysis-understanding-true-product-margins",                      destination: "/blog/cpg-profitability-analysis-understanding-true-product-margins",                      permanent: true },
  { source: "/cpg-profitability-analysis-understanding-true-product-margins/",                     destination: "/blog/cpg-profitability-analysis-understanding-true-product-margins",                      permanent: true },
  { source: "/cpg-regulatory-changes-staying-compliant-in-evolving-markets",                       destination: "/blog/cpg-regulatory-changes-staying-compliant-in-evolving-markets",                       permanent: true },
  { source: "/cpg-regulatory-changes-staying-compliant-in-evolving-markets/",                      destination: "/blog/cpg-regulatory-changes-staying-compliant-in-evolving-markets",                       permanent: true },
  { source: "/cpg-retail-consolidation-adapting-to-fewer-larger-customers",                        destination: "/blog/cpg-retail-consolidation-adapting-to-fewer-larger-customers",                        permanent: true },
  { source: "/cpg-retail-consolidation-adapting-to-fewer-larger-customers/",                       destination: "/blog/cpg-retail-consolidation-adapting-to-fewer-larger-customers",                        permanent: true },
  { source: "/cpg-seo-strategy-how-to-rank-for-product-keywords-and-drive-organic-discovery",      destination: "/blog/cpg-seo-strategy-how-to-rank-for-product-keywords-and-drive-organic-discovery",      permanent: true },
  { source: "/cpg-seo-strategy-how-to-rank-for-product-keywords-and-drive-organic-discovery/",     destination: "/blog/cpg-seo-strategy-how-to-rank-for-product-keywords-and-drive-organic-discovery",      permanent: true },
  { source: "/cpg-supply-chain-disruptions-building-resilience-and-flexibility",                   destination: "/blog/cpg-supply-chain-disruptions-building-resilience-and-flexibility",                   permanent: true },
  { source: "/cpg-supply-chain-disruptions-building-resilience-and-flexibility/",                  destination: "/blog/cpg-supply-chain-disruptions-building-resilience-and-flexibility",                   permanent: true },
  { source: "/cpg-valuation-methods-understanding-what-drives-company-worth",                      destination: "/blog/cpg-valuation-methods-understanding-what-drives-company-worth",                      permanent: true },
  { source: "/cpg-valuation-methods-understanding-what-drives-company-worth/",                     destination: "/blog/cpg-valuation-methods-understanding-what-drives-company-worth",                      permanent: true },
  { source: "/cpg-working-capital-management-optimizing-cash-flow",                                destination: "/blog/cpg-working-capital-management-optimizing-cash-flow",                                permanent: true },
  { source: "/cpg-working-capital-management-optimizing-cash-flow/",                               destination: "/blog/cpg-working-capital-management-optimizing-cash-flow",                               permanent: true },
  { source: "/creating-a-cpg-brand-identity-that-stands-out-on-shelf-and-online",                  destination: "/blog/creating-a-cpg-brand-identity-that-stands-out-on-shelf-and-online",                  permanent: true },
  { source: "/creating-a-cpg-brand-identity-that-stands-out-on-shelf-and-online/",                 destination: "/blog/creating-a-cpg-brand-identity-that-stands-out-on-shelf-and-online",                  permanent: true },
  { source: "/digital-marketing-strategies-for-cpg-brands-a-complete-2025-guide",                  destination: "/blog/digital-marketing-strategies-for-cpg-brands-a-complete-2025-guide",                  permanent: true },
  { source: "/digital-marketing-strategies-for-cpg-brands-a-complete-2025-guide/",                 destination: "/blog/digital-marketing-strategies-for-cpg-brands-a-complete-2025-guide",                  permanent: true },
  { source: "/dtc-marketing-for-cpg-brands-should-your-packaged-goods-brand-sell-direct-to-consumer",  destination: "/blog/dtc-marketing-for-cpg-brands-should-your-packaged-goods-brand-sell-direct-to-consumer",  permanent: true },
  { source: "/dtc-marketing-for-cpg-brands-should-your-packaged-goods-brand-sell-direct-to-consumer/", destination: "/blog/dtc-marketing-for-cpg-brands-should-your-packaged-goods-brand-sell-direct-to-consumer",  permanent: true },
  { source: "/email-marketing-for-cpg-brands-list-building-and-campaign-strategies-that-work",      destination: "/blog/email-marketing-for-cpg-brands-list-building-and-campaign-strategies-that-work",      permanent: true },
  { source: "/email-marketing-for-cpg-brands-list-building-and-campaign-strategies-that-work/",     destination: "/blog/email-marketing-for-cpg-brands-list-building-and-campaign-strategies-that-work",      permanent: true },
  { source: "/facebook-and-instagram-ads-for-cpg-products-creative-and-targeting-best-practices",   destination: "/blog/facebook-and-instagram-ads-for-cpg-products-creative-and-targeting-best-practices",   permanent: true },
  { source: "/facebook-and-instagram-ads-for-cpg-products-creative-and-targeting-best-practices/",  destination: "/blog/facebook-and-instagram-ads-for-cpg-products-creative-and-targeting-best-practices",   permanent: true },
  { source: "/google-shopping-ads-for-cpg-brands-product-feed-optimization-and-campaign-setup",     destination: "/blog/google-shopping-ads-for-cpg-brands-product-feed-optimization-and-campaign-setup",     permanent: true },
  { source: "/google-shopping-ads-for-cpg-brands-product-feed-optimization-and-campaign-setup/",    destination: "/blog/google-shopping-ads-for-cpg-brands-product-feed-optimization-and-campaign-setup",     permanent: true },
  { source: "/influencer-marketing-for-cpg-products-finding-and-working-with-content-creators",     destination: "/blog/influencer-marketing-for-cpg-products-finding-and-working-with-content-creators",     permanent: true },
  { source: "/influencer-marketing-for-cpg-products-finding-and-working-with-content-creators/",    destination: "/blog/influencer-marketing-for-cpg-products-finding-and-working-with-content-creators",     permanent: true },
  { source: "/premium-vs-value-cpg-positioning-pricing-strategy-and-marketing-implications",        destination: "/blog/premium-vs-value-cpg-positioning-pricing-strategy-and-marketing-implications",        permanent: true },
  { source: "/premium-vs-value-cpg-positioning-pricing-strategy-and-marketing-implications/",       destination: "/blog/premium-vs-value-cpg-positioning-pricing-strategy-and-marketing-implications",        permanent: true },
  { source: "/private-label-vs-branded-cpg-marketing-strategies-for-each-approach",                 destination: "/blog/private-label-vs-branded-cpg-marketing-strategies-for-each-approach",                 permanent: true },
  { source: "/private-label-vs-branded-cpg-marketing-strategies-for-each-approach/",                destination: "/blog/private-label-vs-branded-cpg-marketing-strategies-for-each-approach",                 permanent: true },
  { source: "/retail-media-networks-for-cpg-walmart-connect-target-roundel-and-instacart-ads",      destination: "/blog/retail-media-networks-for-cpg-walmart-connect-target-roundel-and-instacart-ads",      permanent: true },
  { source: "/retail-media-networks-for-cpg-walmart-connect-target-roundel-and-instacart-ads/",     destination: "/blog/retail-media-networks-for-cpg-walmart-connect-target-roundel-and-instacart-ads",      permanent: true },
  { source: "/shipping-and-fulfillment-marketing-for-cpg-brands-making-logistics-a-competitive-advantage",  destination: "/blog/shipping-and-fulfillment-marketing-for-cpg-brands-making-logistics-a-competitive-advantage",  permanent: true },
  { source: "/shipping-and-fulfillment-marketing-for-cpg-brands-making-logistics-a-competitive-advantage/", destination: "/blog/shipping-and-fulfillment-marketing-for-cpg-brands-making-logistics-a-competitive-advantage",  permanent: true },
  { source: "/shopify-for-cpg-brands-building-a-direct-to-consumer-ecommerce-strategy",             destination: "/blog/shopify-for-cpg-brands-building-a-direct-to-consumer-ecommerce-strategy",             permanent: true },
  { source: "/shopify-for-cpg-brands-building-a-direct-to-consumer-ecommerce-strategy/",            destination: "/blog/shopify-for-cpg-brands-building-a-direct-to-consumer-ecommerce-strategy",             permanent: true },
  { source: "/social-media-marketing-for-cpg-brands-platform-strategies-that-drive-sales",          destination: "/blog/social-media-marketing-for-cpg-brands-platform-strategies-that-drive-sales",          permanent: true },
  { source: "/social-media-marketing-for-cpg-brands-platform-strategies-that-drive-sales/",         destination: "/blog/social-media-marketing-for-cpg-brands-platform-strategies-that-drive-sales",          permanent: true },
  { source: "/sustainable-cpg-marketing-how-eco-friendly-positioning-drives-sales-in-2025",          destination: "/blog/sustainable-cpg-marketing-how-eco-friendly-positioning-drives-sales-in-2025",          permanent: true },
  { source: "/sustainable-cpg-marketing-how-eco-friendly-positioning-drives-sales-in-2025/",         destination: "/blog/sustainable-cpg-marketing-how-eco-friendly-positioning-drives-sales-in-2025",          permanent: true },
  { source: "/user-generated-content-for-cpg-turning-customers-into-brand-advocates",               destination: "/blog/user-generated-content-for-cpg-turning-customers-into-brand-advocates",               permanent: true },
  { source: "/user-generated-content-for-cpg-turning-customers-into-brand-advocates/",              destination: "/blog/user-generated-content-for-cpg-turning-customers-into-brand-advocates",               permanent: true },
  { source: "/video-marketing-for-cpg-brands-youtube-tiktok-and-short-form-content-strategies",     destination: "/blog/video-marketing-for-cpg-brands-youtube-tiktok-and-short-form-content-strategies",     permanent: true },
  { source: "/video-marketing-for-cpg-brands-youtube-tiktok-and-short-form-content-strategies/",    destination: "/blog/video-marketing-for-cpg-brands-youtube-tiktok-and-short-form-content-strategies",     permanent: true },

  // ── Blog posts that DON'T exist on new site — send to /blog ────────────────
  { source: "/convenience-store-marketing-for-cpg-brands-strategies-for-c-store-success",           destination: "/blog", permanent: true },
  { source: "/convenience-store-marketing-for-cpg-brands-strategies-for-c-store-success/",          destination: "/blog", permanent: true },
  { source: "/big-box-retail-marketing-getting-your-cpg-products-into-target-walmart-and-costco",   destination: "/blog", permanent: true },
  { source: "/big-box-retail-marketing-getting-your-cpg-products-into-target-walmart-and-costco/",  destination: "/blog", permanent: true },
  { source: "/amazon-marketing-for-cpg-brands-winning-the-digital-shelf-in-2025",                   destination: "/blog", permanent: true },
  { source: "/amazon-marketing-for-cpg-brands-winning-the-digital-shelf-in-2025/",                  destination: "/blog", permanent: true },
  { source: "/cpg-financial-metrics-kpis-every-brand-should-track",                                 destination: "/blog", permanent: true },
  { source: "/cpg-financial-metrics-kpis-every-brand-should-track/",                                destination: "/blog", permanent: true },
  { source: "/cpg-marketing-agency-the-complete-guide-to-choosing-the-right-marketing-partner-for-your-consumer-packaged-goods-brand",  destination: "/cpg",  permanent: true },
  { source: "/cpg-marketing-agency-the-complete-guide-to-choosing-the-right-marketing-partner-for-your-consumer-packaged-goods-brand/", destination: "/cpg",  permanent: true },
  { source: "/what-is-cpg-marketing-a-complete-guide-for-consumer-packaged-goods-brands",           destination: "/cpg",  permanent: true },
  { source: "/what-is-cpg-marketing-a-complete-guide-for-consumer-packaged-goods-brands/",          destination: "/cpg",  permanent: true },
  { source: "/cpg-vs-traditional-marketing-key-differences-every-brand-owner-should-know",          destination: "/blog", permanent: true },
  { source: "/cpg-vs-traditional-marketing-key-differences-every-brand-owner-should-know/",         destination: "/blog", permanent: true },
  { source: "/the-cpg-customer-journey-understanding-how-consumers-buy-packaged-goods-in-2025",     destination: "/blog", permanent: true },
  { source: "/the-cpg-customer-journey-understanding-how-consumers-buy-packaged-goods-in-2025/",    destination: "/blog", permanent: true },
  { source: "/retail-marketing-strategies-for-cpg-brands-how-to-win-at-point-of-purchase",          destination: "/blog", permanent: true },
  { source: "/retail-marketing-strategies-for-cpg-brands-how-to-win-at-point-of-purchase/",         destination: "/blog", permanent: true },
  { source: "/cpg-market-trends-2025-what-consumer-packaged-goods-brands-need-to-know",             destination: "/blog", permanent: true },
  { source: "/cpg-market-trends-2025-what-consumer-packaged-goods-brands-need-to-know/",            destination: "/blog", permanent: true },
  { source: "/trade-marketing-for-cpg-brands-working-with-retailers-to-drive-sales",                destination: "/blog", permanent: true },
  { source: "/trade-marketing-for-cpg-brands-working-with-retailers-to-drive-sales/",               destination: "/blog", permanent: true },
  { source: "/how-cpg-marketing-has-changed-from-traditional-retail-to-dtc-and-omnichannel",        destination: "/blog", permanent: true },
  { source: "/how-cpg-marketing-has-changed-from-traditional-retail-to-dtc-and-omnichannel/",       destination: "/blog", permanent: true },
  { source: "/cpg-slotting-fees-and-retail-partnerships-what-brands-need-to-budget-for",            destination: "/blog", permanent: true },
  { source: "/cpg-slotting-fees-and-retail-partnerships-what-brands-need-to-budget-for/",           destination: "/blog", permanent: true },
  { source: "/cpg-category-management-how-marketing-agencies-help-brands-win-shelf-space",          destination: "/blog", permanent: true },
  { source: "/cpg-category-management-how-marketing-agencies-help-brands-win-shelf-space/",         destination: "/blog", permanent: true },
  { source: "/the-role-of-a-cpg-marketing-agency-services-strategy-and-roi-explained",              destination: "/cpg",  permanent: true },
  { source: "/the-role-of-a-cpg-marketing-agency-services-strategy-and-roi-explained/",             destination: "/cpg",  permanent: true },
  { source: "/retail-merchandising-for-cpg-in-store-displays-endcaps-and-promotional-strategies",   destination: "/blog", permanent: true },
  { source: "/retail-merchandising-for-cpg-in-store-displays-endcaps-and-promotional-strategies/",  destination: "/blog", permanent: true },
  { source: "/omnichannel-cpg-marketing-connecting-retail-dtc-and-online-marketplaces",             destination: "/blog", permanent: true },
  { source: "/omnichannel-cpg-marketing-connecting-retail-dtc-and-online-marketplaces/",            destination: "/blog", permanent: true },
  { source: "/subscription-models-for-cpg-products-how-to-launch-and-market-a-cpg-subscription-business",  destination: "/blog", permanent: true },
  { source: "/subscription-models-for-cpg-products-how-to-launch-and-market-a-cpg-subscription-business/", destination: "/blog", permanent: true },

  // ── Agency ops blog posts (51 posts) — all redirect to /blog ─────────────
  { source: "/ppc-agency-services-managing-paid-advertising-campaigns-profitably",                  destination: "/blog", permanent: true },
  { source: "/ppc-agency-services-managing-paid-advertising-campaigns-profitably/",                 destination: "/blog", permanent: true },
  { source: "/content-marketing-agency-creating-scalable-content-solutions-for-clients",            destination: "/blog", permanent: true },
  { source: "/content-marketing-agency-creating-scalable-content-solutions-for-clients/",           destination: "/blog", permanent: true },
  { source: "/email-marketing-agency-building-a-specialized-email-services-business",               destination: "/blog", permanent: true },
  { source: "/email-marketing-agency-building-a-specialized-email-services-business/",              destination: "/blog", permanent: true },
  { source: "/influencer-marketing-agency-connecting-brands-with-content-creators",                 destination: "/blog", permanent: true },
  { source: "/influencer-marketing-agency-connecting-brands-with-content-creators/",                destination: "/blog", permanent: true },
  { source: "/branding-agency-vs-marketing-agency-understanding-the-key-differences",               destination: "/services/branding", permanent: true },
  { source: "/branding-agency-vs-marketing-agency-understanding-the-key-differences/",              destination: "/services/branding", permanent: true },
  { source: "/niche-marketing-agency-benefits-of-specializing-in-one-industry",                     destination: "/blog", permanent: true },
  { source: "/niche-marketing-agency-benefits-of-specializing-in-one-industry/",                    destination: "/blog", permanent: true },
  { source: "/how-to-start-a-marketing-agency-step-by-step-launch-guide",                           destination: "/blog", permanent: true },
  { source: "/how-to-start-a-marketing-agency-step-by-step-launch-guide/",                          destination: "/blog", permanent: true },
  { source: "/marketing-agency-business-plan-essential-components-for-success",                     destination: "/blog", permanent: true },
  { source: "/marketing-agency-business-plan-essential-components-for-success/",                    destination: "/blog", permanent: true },
  { source: "/marketing-agency-pricing-models-retainer-project-and-performance-based-options",      destination: "/blog", permanent: true },
  { source: "/marketing-agency-pricing-models-retainer-project-and-performance-based-options/",     destination: "/blog", permanent: true },
  { source: "/marketing-agency-legal-requirements-contracts-insurance-and-business-structure",       destination: "/blog", permanent: true },
  { source: "/marketing-agency-legal-requirements-contracts-insurance-and-business-structure/",      destination: "/blog", permanent: true },
  { source: "/marketing-agency-guide-complete-resource-for-starting-growing-and-scaling-your-agency",  destination: "/blog", permanent: true },
  { source: "/marketing-agency-guide-complete-resource-for-starting-growing-and-scaling-your-agency/", destination: "/blog", permanent: true },
  { source: "/digital-marketing-agency-services-business-model-and-growth-strategies",               destination: "/services", permanent: true },
  { source: "/digital-marketing-agency-services-business-model-and-growth-strategies/",              destination: "/services", permanent: true },
  { source: "/full-service-marketing-agency-building-comprehensive-client-solutions",                destination: "/services", permanent: true },
  { source: "/full-service-marketing-agency-building-comprehensive-client-solutions/",               destination: "/services", permanent: true },
  { source: "/social-media-marketing-agency-how-to-specialize-and-scale-in-social",                 destination: "/services/paid-media", permanent: true },
  { source: "/social-media-marketing-agency-how-to-specialize-and-scale-in-social/",                destination: "/services/paid-media", permanent: true },
  { source: "/seo-agency-business-model-delivering-search-results-for-clients",                     destination: "/services/seo-aeo", permanent: true },
  { source: "/seo-agency-business-model-delivering-search-results-for-clients/",                    destination: "/services/seo-aeo", permanent: true },
  { source: "/marketing-agency-lead-generation-strategies-that-actually-work",                      destination: "/blog", permanent: true },
  { source: "/marketing-agency-lead-generation-strategies-that-actually-work/",                     destination: "/blog", permanent: true },
  { source: "/marketing-agency-sales-process-from-prospect-to-signed-contract",                     destination: "/blog", permanent: true },
  { source: "/marketing-agency-sales-process-from-prospect-to-signed-contract/",                    destination: "/blog", permanent: true },
  { source: "/marketing-agency-proposal-writing-creating-winning-client-proposals",                  destination: "/blog", permanent: true },
  { source: "/marketing-agency-proposal-writing-creating-winning-client-proposals/",                 destination: "/blog", permanent: true },
  { source: "/marketing-agency-case-studies-showcasing-results-to-win-more-business",               destination: "/work", permanent: true },
  { source: "/marketing-agency-case-studies-showcasing-results-to-win-more-business/",              destination: "/work", permanent: true },
  { source: "/marketing-agency-referral-program-turning-clients-into-your-sales-team",              destination: "/blog", permanent: true },
  { source: "/marketing-agency-referral-program-turning-clients-into-your-sales-team/",             destination: "/blog", permanent: true },
  { source: "/marketing-agency-cold-outreach-email-and-linkedin-strategies-that-convert",           destination: "/blog", permanent: true },
  { source: "/marketing-agency-cold-outreach-email-and-linkedin-strategies-that-convert/",          destination: "/blog", permanent: true },
  { source: "/marketing-agency-discovery-calls-qualifying-and-converting-prospects",                destination: "/blog", permanent: true },
  { source: "/marketing-agency-discovery-calls-qualifying-and-converting-prospects/",               destination: "/blog", permanent: true },
  { source: "/marketing-agency-pricing-presentation-how-to-justify-your-value",                     destination: "/blog", permanent: true },
  { source: "/marketing-agency-pricing-presentation-how-to-justify-your-value/",                    destination: "/blog", permanent: true },
  { source: "/marketing-agency-portfolio-development-building-credibility-without-clients",          destination: "/work", permanent: true },
  { source: "/marketing-agency-portfolio-development-building-credibility-without-clients/",         destination: "/work", permanent: true },
  { source: "/marketing-agency-networking-strategies-building-relationships-that-generate-revenue",  destination: "/blog", permanent: true },
  { source: "/marketing-agency-networking-strategies-building-relationships-that-generate-revenue/", destination: "/blog", permanent: true },
  { source: "/marketing-agency-initial-investment-startup-costs-and-funding-options",               destination: "/blog", permanent: true },
  { source: "/marketing-agency-initial-investment-startup-costs-and-funding-options/",              destination: "/blog", permanent: true },
  { source: "/marketing-agency-client-onboarding-setting-up-projects-for-success",                  destination: "/blog", permanent: true },
  { source: "/marketing-agency-client-onboarding-setting-up-projects-for-success/",                 destination: "/blog", permanent: true },
  { source: "/choosing-your-marketing-agency-niche-finding-your-ideal-focus-area",                  destination: "/blog", permanent: true },
  { source: "/choosing-your-marketing-agency-niche-finding-your-ideal-focus-area/",                 destination: "/blog", permanent: true },
  { source: "/marketing-agency-project-management-tools-and-workflows-that-scale",                  destination: "/blog", permanent: true },
  { source: "/marketing-agency-project-management-tools-and-workflows-that-scale/",                 destination: "/blog", permanent: true },
  { source: "/marketing-agency-name-and-branding-creating-a-memorable-identity",                    destination: "/services/branding", permanent: true },
  { source: "/marketing-agency-name-and-branding-creating-a-memorable-identity/",                   destination: "/services/branding", permanent: true },
  { source: "/marketing-agency-reporting-creating-client-dashboards-that-demonstrate-value",         destination: "/blog", permanent: true },
  { source: "/marketing-agency-reporting-creating-client-dashboards-that-demonstrate-value/",        destination: "/blog", permanent: true },
  { source: "/marketing-agency-website-design-converting-visitors-into-qualified-leads",             destination: "/services/web-design", permanent: true },
  { source: "/marketing-agency-website-design-converting-visitors-into-qualified-leads/",            destination: "/services/web-design", permanent: true },
  { source: "/marketing-agency-sops-documenting-processes-for-consistency",                         destination: "/blog", permanent: true },
  { source: "/marketing-agency-sops-documenting-processes-for-consistency/",                        destination: "/blog", permanent: true },
  { source: "/building-your-agency-service-menu-what-to-offer-and-what-to-avoid",                   destination: "/services", permanent: true },
  { source: "/building-your-agency-service-menu-what-to-offer-and-what-to-avoid/",                  destination: "/services", permanent: true },
  { source: "/solo-marketing-consultant-to-agency-making-the-transition-successfully",               destination: "/blog", permanent: true },
  { source: "/solo-marketing-consultant-to-agency-making-the-transition-successfully/",              destination: "/blog", permanent: true },
  { source: "/marketing-agency-time-tracking-understanding-profitability-by-project",               destination: "/blog", permanent: true },
  { source: "/marketing-agency-time-tracking-understanding-profitability-by-project/",              destination: "/blog", permanent: true },
  { source: "/marketing-agency-scope-creep-preventing-and-managing-client-expansion-requests",      destination: "/blog", permanent: true },
  { source: "/marketing-agency-scope-creep-preventing-and-managing-client-expansion-requests/",     destination: "/blog", permanent: true },
  { source: "/marketing-agency-client-retention-strategies-to-reduce-churn",                        destination: "/blog", permanent: true },
  { source: "/marketing-agency-client-retention-strategies-to-reduce-churn/",                       destination: "/blog", permanent: true },
  { source: "/marketing-agency-offboarding-managing-client-departures-professionally",               destination: "/blog", permanent: true },
  { source: "/marketing-agency-offboarding-managing-client-departures-professionally/",              destination: "/blog", permanent: true },
  { source: "/hiring-for-your-marketing-agency-finding-top-talent",                                  destination: "/about", permanent: true },
  { source: "/hiring-for-your-marketing-agency-finding-top-talent/",                                 destination: "/about", permanent: true },
  { source: "/marketing-agency-organizational-structure-building-an-efficient-team",                 destination: "/about", permanent: true },
  { source: "/marketing-agency-organizational-structure-building-an-efficient-team/",                destination: "/about", permanent: true },
  { source: "/marketing-agency-contractor-vs-employee-making-the-right-choice",                     destination: "/blog", permanent: true },
  { source: "/marketing-agency-contractor-vs-employee-making-the-right-choice/",                    destination: "/blog", permanent: true },
  { source: "/marketing-agency-remote-team-management-leading-distributed-workers",                  destination: "/blog", permanent: true },
  { source: "/marketing-agency-remote-team-management-leading-distributed-workers/",                 destination: "/blog", permanent: true },
  { source: "/marketing-agency-training-programs-developing-skilled-team-members",                   destination: "/blog", permanent: true },
  { source: "/marketing-agency-training-programs-developing-skilled-team-members/",                  destination: "/blog", permanent: true },
  { source: "/marketing-agency-performance-reviews-evaluating-and-motivating-staff",                 destination: "/blog", permanent: true },
  { source: "/marketing-agency-performance-reviews-evaluating-and-motivating-staff/",                destination: "/blog", permanent: true },
  { source: "/marketing-agency-compensation-plans-salary-commission-and-bonus-structures",           destination: "/blog", permanent: true },
  { source: "/marketing-agency-compensation-plans-salary-commission-and-bonus-structures/",          destination: "/blog", permanent: true },
  { source: "/marketing-agency-culture-creating-an-environment-that-attracts-talent",               destination: "/blog", permanent: true },
  { source: "/marketing-agency-culture-creating-an-environment-that-attracts-talent/",              destination: "/blog", permanent: true },
  { source: "/marketing-agency-account-manager-role-responsibilities-and-best-practices",            destination: "/blog", permanent: true },
  { source: "/marketing-agency-account-manager-role-responsibilities-and-best-practices/",           destination: "/blog", permanent: true },
  { source: "/marketing-agency-creative-team-management-balancing-quality-and-efficiency",           destination: "/blog", permanent: true },
  { source: "/marketing-agency-creative-team-management-balancing-quality-and-efficiency/",          destination: "/blog", permanent: true },
  { source: "/marketing-agency-quality-control-maintaining-standards-across-all-clients",            destination: "/blog", permanent: true },
  { source: "/marketing-agency-quality-control-maintaining-standards-across-all-clients/",           destination: "/blog", permanent: true },
  { source: "/marketing-agency-communication-systems-managing-client-expectations",                  destination: "/blog", permanent: true },
  { source: "/marketing-agency-communication-systems-managing-client-expectations/",                 destination: "/blog", permanent: true },

  // ── GSC crawl cleanup (Jun 2026) — old WP posts still being crawled ───────────
  // Posts that exist on the new site → map to the real /blog post
  { source: "/cpg-manufacturing-excellence-ensuring-quality-and-consistency-at-scale",   destination: "/blog/cpg-manufacturing-excellence-ensuring-quality-and-consistency-at-scale", permanent: true },
  { source: "/cpg-manufacturing-excellence-ensuring-quality-and-consistency-at-scale/",  destination: "/blog/cpg-manufacturing-excellence-ensuring-quality-and-consistency-at-scale", permanent: true },
  { source: "/cpg-test-marketing-validating-products-before-national-rollout",           destination: "/blog/cpg-test-marketing-validating-products-before-national-rollout", permanent: true },
  { source: "/cpg-test-marketing-validating-products-before-national-rollout/",          destination: "/blog/cpg-test-marketing-validating-products-before-national-rollout", permanent: true },

  // Old landing page → CPG hub
  { source: "/strategic-cpg-consumer-packaged-goods-marketing",                          destination: "/cpg", permanent: true },
  { source: "/strategic-cpg-consumer-packaged-goods-marketing/",                         destination: "/cpg", permanent: true },

  // Dead WP blog posts (never migrated) → blog index
  { source: "/pet-care-cpg-products-capturing-growth-in-the-expanding-pet-industry",     destination: "/blog", permanent: true },
  { source: "/pet-care-cpg-products-capturing-growth-in-the-expanding-pet-industry/",    destination: "/blog", permanent: true },
  { source: "/cpg-consumer-behavior-analysis-understanding-purchase-decision-drivers",   destination: "/blog", permanent: true },
  { source: "/cpg-consumer-behavior-analysis-understanding-purchase-decision-drivers/",  destination: "/blog", permanent: true },
  { source: "/over-the-counter-pharmaceuticals-navigating-the-cpg-healthcare-market",    destination: "/blog", permanent: true },
  { source: "/over-the-counter-pharmaceuticals-navigating-the-cpg-healthcare-market/",   destination: "/blog", permanent: true },
  { source: "/cpg-brand-positioning-how-to-differentiate-in-crowded-markets",            destination: "/blog/cpg-brand-positioning-how-to-differentiate-in-crowded-markets", permanent: true },
  { source: "/cpg-brand-positioning-how-to-differentiate-in-crowded-markets/",           destination: "/blog/cpg-brand-positioning-how-to-differentiate-in-crowded-markets", permanent: true },
  { source: "/consumer-packaged-goods-guide-complete-industry-overview-for-brands-retailers-and-investors",  destination: "/blog/consumer-packaged-goods-guide-complete-industry-overview-for-brands-retailers-and-investors", permanent: true },
  { source: "/consumer-packaged-goods-guide-complete-industry-overview-for-brands-retailers-and-investors/", destination: "/blog/consumer-packaged-goods-guide-complete-industry-overview-for-brands-retailers-and-investors", permanent: true },
  { source: "/cpg-distribution-channels-choosing-between-retail-dtc-and-hybrid-models",  destination: "/blog/cpg-distribution-channels-choosing-between-retail-dtc-and-hybrid-models", permanent: true },
  { source: "/cpg-distribution-channels-choosing-between-retail-dtc-and-hybrid-models/", destination: "/blog/cpg-distribution-channels-choosing-between-retail-dtc-and-hybrid-models", permanent: true },
  { source: "/household-cleaning-products-cpg-strategies-for-essential-home-goods",      destination: "/blog", permanent: true },
  { source: "/household-cleaning-products-cpg-strategies-for-essential-home-goods/",     destination: "/blog", permanent: true },
  { source: "/cpg-quality-control-maintaining-standards-and-consumer-safety",            destination: "/blog", permanent: true },
  { source: "/cpg-quality-control-maintaining-standards-and-consumer-safety/",           destination: "/blog", permanent: true },
  { source: "/cpg-co-packing-vs-in-house-production-making-the-right-choice",            destination: "/blog", permanent: true },
  { source: "/cpg-co-packing-vs-in-house-production-making-the-right-choice/",           destination: "/blog", permanent: true },
  { source: "/health-and-wellness-cpg-trends-capitalizing-on-clean-label-movement",     destination: "/blog", permanent: true },
  { source: "/health-and-wellness-cpg-trends-capitalizing-on-clean-label-movement/",    destination: "/blog", permanent: true },
  { source: "/cpg-regulatory-compliance-navigating-fda-epa-and-industry-requirements",  destination: "/blog", permanent: true },
  { source: "/cpg-regulatory-compliance-navigating-fda-epa-and-industry-requirements/", destination: "/blog", permanent: true },
  { source: "/cpg-ingredient-sourcing-building-reliable-supply-networks",               destination: "/blog", permanent: true },
  { source: "/cpg-ingredient-sourcing-building-reliable-supply-networks/",              destination: "/blog", permanent: true },
  { source: "/cpg-sales-forecasting-predicting-demand-and-managing-inventory",          destination: "/blog", permanent: true },
  { source: "/cpg-sales-forecasting-predicting-demand-and-managing-inventory/",         destination: "/blog", permanent: true },
  { source: "/cpg-product-launch-strategy-ensuring-successful-market-introductions",    destination: "/blog", permanent: true },
  { source: "/cpg-product-launch-strategy-ensuring-successful-market-introductions/",   destination: "/blog", permanent: true },
  { source: "/cpg-market-research-methods-understanding-your-target-consumer",          destination: "/blog/cpg-market-research-methods-understanding-your-target-consumer", permanent: true },
  { source: "/cpg-market-research-methods-understanding-your-target-consumer/",         destination: "/blog/cpg-market-research-methods-understanding-your-target-consumer", permanent: true },
  { source: "/cpg-data-analytics-using-insights-to-drive-business-decisions",           destination: "/blog", permanent: true },
  { source: "/cpg-data-analytics-using-insights-to-drive-business-decisions/",          destination: "/blog", permanent: true },
];

const nextConfig: NextConfig = {
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: securityHeaders,
      },
    ];
  },
  async redirects() {
    return redirects;
  },
};

export default nextConfig;
